### ISSUE TITLE
bug in toml reformat

### ISSUE THREAD

**Issue by cstria0106** [ZasEditor/Zas-Editor-Issues#39]
## my code

```toml
[package]
name = "my-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tokio-tungstenite = "0.17"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.3"
anyhow = "1.0"
```

## after reformat
```toml
[package]
name = "my-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tokio-tungstenite = "0.17"
```
